using System.Data;
using System.Globalization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Shapes;
using BabyShop.Configuration;
using BabyShop.Infrastructure;
using BabyShop.Localization;
using BabyShop.Models;
using BabyShop.Repositories;

namespace BabyShop;

public partial class DashboardWindow : Window
{
    private const string DashboardOrderDetailsColumnSortKey = "__dashboard_order_details_action";

    private enum AmountDragTarget
    {
        None,
        Minimum,
        Maximum
    }

    private static readonly Brush[] ChartBrushes =
    [
        new SolidColorBrush(Color.FromRgb(215, 125, 145)),
        new SolidColorBrush(Color.FromRgb(111, 169, 146)),
        new SolidColorBrush(Color.FromRgb(226, 184, 97)),
        new SolidColorBrush(Color.FromRgb(142, 188, 214)),
        new SolidColorBrush(Color.FromRgb(224, 158, 128)),
        new SolidColorBrush(Color.FromRgb(166, 139, 188))
    ];

    private readonly BabyShopRepository _repository;
    private bool _isBusy;
    private bool _isUpdatingAmountControls;
    private decimal _amountSliderMinimum;
    private decimal _amountSliderMaximum = 1m;
    private decimal _selectedMinAmount;
    private decimal _selectedMaxAmount = 1m;
    private AmountDragTarget _amountDragTarget;
    private List<LookupOption> _clientOptions = [];
    private List<LookupOption> _productOptions = [];
    private List<LookupOption> _fabricOptions = [];
    private IReadOnlyList<DashboardSeriesPoint> _statusPoints = [];
    private IReadOnlyList<DashboardSeriesPoint> _categoryPoints = [];
    private IReadOnlyList<DashboardSeriesPoint> _timelinePoints = [];
    private IReadOnlyList<DashboardSeriesPoint> _monthPoints = [];

    public DashboardWindow()
    {
        InitializeComponent();
        WindowAppearance.ApplySharedIcon(this);
        _repository = new BabyShopRepository(new DbHelper(DatabaseSettings.BuildConnectionString()));
        DashboardDataGrid.AutoGeneratedColumns += DashboardDataGrid_AutoGeneratedColumns;
        SizeChanged += DashboardWindow_SizeChanged;
        LanguageManager.LanguageChanged += LanguageManager_LanguageChanged;
        ApplyLocalization();
    }

    private async void Window_Loaded(object sender, RoutedEventArgs e)
    {
        await InitializeAsync();
    }

    private async Task InitializeAsync()
    {
        SetBusyState(true);

        try
        {
            await LoadFilterOptionsAsync();
            await LoadAmountFilterBoundsAsync();
            await LoadDashboardAsync();
        }
        catch (Exception exception)
        {
            MessageBox.Show(exception.Message, LanguageManager.Get("Dashboard"), MessageBoxButton.OK, MessageBoxImage.Error);
            DashboardStatusTextBlock.Text = exception.Message;
        }
        finally
        {
            SetBusyState(false);
        }
    }

    private async Task LoadFilterOptionsAsync()
    {
        var clientsTask = _repository.GetDashboardLookupOptionsAsync("c_fullname");
        var productsTask = _repository.GetDashboardLookupOptionsAsync("product_title");
        var fabricsTask = _repository.GetDashboardLookupOptionsAsync("fabric_type");

        await Task.WhenAll(clientsTask, productsTask, fabricsTask);

        _clientOptions = clientsTask.Result.ToList();
        _productOptions = productsTask.Result.ToList();
        _fabricOptions = fabricsTask.Result.ToList();

        RefreshFilterItems();
    }

    private async Task LoadAmountFilterBoundsAsync()
    {
        var bounds = await _repository.GetDashboardAmountBoundsAsync();
        ConfigureAmountSliders(bounds.Minimum, bounds.Maximum);
    }

    private void ConfigureAmountSliders(decimal minimum, decimal maximum)
    {
        if (maximum <= minimum)
        {
            maximum = minimum + 1m;
        }

        _amountSliderMinimum = minimum;
        _amountSliderMaximum = maximum;
        _selectedMinAmount = minimum;
        _selectedMaxAmount = maximum;

        _isUpdatingAmountControls = true;
        MinPriceTextBox.Text = FormatMoney(minimum);
        MaxPriceTextBox.Text = FormatMoney(maximum);
        UpdateAmountSliderLabels();
        UpdateAmountRangeVisual();
        _isUpdatingAmountControls = false;
    }

    private void RefreshFilterItems()
    {
        var selectedClient = ClientComboBox.SelectedValue as string;
        var selectedStatus = StatusComboBox.SelectedValue as string;
        var selectedProduct = ProductComboBox.SelectedValue as string;
        var selectedFabric = FabricTypeComboBox.SelectedValue as string;

        ClientComboBox.ItemsSource = BuildOptionsWithAll(_clientOptions, "AllClients");
        ProductComboBox.ItemsSource = BuildOptionsWithAll(_productOptions, "AllProducts");
        FabricTypeComboBox.ItemsSource = BuildOptionsWithAll(_fabricOptions, "AllFabricTypes");
        StatusComboBox.ItemsSource = BuildStatusOptions();

        ClientComboBox.SelectedValue = selectedClient;
        StatusComboBox.SelectedValue = selectedStatus;
        ProductComboBox.SelectedValue = selectedProduct;
        FabricTypeComboBox.SelectedValue = selectedFabric;
    }

    private async Task LoadDashboardAsync()
    {
        var filter = ReadFilter();
        var hasStatusFilter = !string.IsNullOrWhiteSpace(filter.Status);

        var dataTask = _repository.GetDashboardDataAsync(filter);
        var summaryTask = _repository.GetDashboardSummaryAsync(filter);
        var statusTask = hasStatusFilter
            ? Task.FromResult<IReadOnlyList<DashboardSeriesPoint>>([])
            : _repository.GetDashboardStatusChartAsync(filter);
        var categoryTask = _repository.GetDashboardCategoryChartAsync(filter);
        var timelineTask = _repository.GetDashboardTimelineChartAsync(filter);
        var monthTask = _repository.GetDashboardMonthStatsAsync(filter);

        await Task.WhenAll(dataTask, summaryTask, statusTask, categoryTask, timelineTask, monthTask);

        DashboardDataGrid.ItemsSource = dataTask.Result.DefaultView;
        ApplyDashboardSummary(summaryTask.Result);

        _statusPoints = statusTask.Result;
        _categoryPoints = categoryTask.Result;
        _timelinePoints = timelineTask.Result;
        _monthPoints = monthTask.Result;

        UpdateChartLayout(hasStatusFilter);
        if (!hasStatusFilter)
        {
            RenderStatusPieChart(_statusPoints);
        }
        else
        {
            StatusPieCanvas.Children.Clear();
            StatusLegendPanel.Children.Clear();
        }

        RenderBarChart(ProductChartPanel, _categoryPoints, ChartBrushes[0], "DashboardNoCategoryData");
        RenderTimelineChart(_timelinePoints);
        RenderMonthHistogram(_monthPoints);

        DashboardStatusTextBlock.Text = LanguageManager.Format("DashboardRowsLoaded", dataTask.Result.Rows.Count);
    }

    private DashboardFilter ReadFilter()
    {
        var dateFrom = DateFromPicker.SelectedDate;
        var dateTo = DateToPicker.SelectedDate;

        if (dateFrom.HasValue && dateTo.HasValue && dateFrom > dateTo)
        {
            throw new InvalidOperationException(LanguageManager.Get("DashboardDateRangeError"));
        }

        var minPrice = ParseNullableDecimal(MinPriceTextBox.Text, "DashboardMinAmount");
        var maxPrice = ParseNullableDecimal(MaxPriceTextBox.Text, "DashboardMaxAmount");
        if (minPrice.HasValue && maxPrice.HasValue && minPrice > maxPrice)
        {
            throw new InvalidOperationException(LanguageManager.Get("DashboardAmountRangeError"));
        }

        return new DashboardFilter
        {
            DateFrom = dateFrom,
            DateTo = dateTo,
            Status = ReadSelectedValue(StatusComboBox),
            ClientName = ReadSelectedValue(ClientComboBox),
            ProductTitle = ReadSelectedValue(ProductComboBox),
            FabricType = ReadSelectedValue(FabricTypeComboBox),
            MinPrice = minPrice,
            MaxPrice = maxPrice
        };
    }

    private static string? ReadSelectedValue(ComboBox comboBox)
    {
        var value = comboBox.SelectedValue as string;
        return string.IsNullOrWhiteSpace(value) ? null : value;
    }

    private static decimal? ParseNullableDecimal(string text, string fieldKey)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return null;
        }

        if (decimal.TryParse(text, NumberStyles.Number, CultureInfo.CurrentCulture, out var currentValue))
        {
            return currentValue;
        }

        if (decimal.TryParse(text, NumberStyles.Number, CultureInfo.InvariantCulture, out var invariantValue))
        {
            return invariantValue;
        }

        throw new InvalidOperationException(LanguageManager.Format("NumericValidation", LanguageManager.Get(fieldKey)));
    }

    private static bool TryParseNullableDecimal(string text, out decimal? value)
    {
        value = null;
        if (string.IsNullOrWhiteSpace(text))
        {
            return true;
        }

        if (decimal.TryParse(text, NumberStyles.Number, CultureInfo.CurrentCulture, out var currentValue))
        {
            value = currentValue;
            return true;
        }

        if (decimal.TryParse(text, NumberStyles.Number, CultureInfo.InvariantCulture, out var invariantValue))
        {
            value = invariantValue;
            return true;
        }

        return false;
    }

    private void ApplyDashboardSummary(DashboardSummary summary)
    {
        TotalRevenueValueTextBlock.Text = FormatMoney(summary.TotalSum);
        OrdersCountValueTextBlock.Text = summary.OrderCount.ToString("N0", CultureInfo.CurrentCulture);
        AverageCheckValueTextBlock.Text = FormatMoney(summary.AverageValue);
        RangeValueTextBlock.Text = $"{FormatMoney(summary.MinValue)} - {FormatMoney(summary.MaxValue)}";
    }

    private void AmountThumb_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
    {
        if (_isBusy)
        {
            return;
        }

        _amountDragTarget = ReferenceEquals(sender, MinAmountThumb)
            ? AmountDragTarget.Minimum
            : AmountDragTarget.Maximum;
        AmountRangeCanvas.CaptureMouse();
        e.Handled = true;
    }

    private void AmountRangeCanvas_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
    {
        if (_isBusy)
        {
            return;
        }

        var clickValue = AmountFromCanvasX(e.GetPosition(AmountRangeCanvas).X);
        _amountDragTarget = Math.Abs(clickValue - _selectedMinAmount) <= Math.Abs(clickValue - _selectedMaxAmount)
            ? AmountDragTarget.Minimum
            : AmountDragTarget.Maximum;

        SetSelectedAmount(_amountDragTarget, clickValue, updateTextBoxes: true);
        AmountRangeCanvas.CaptureMouse();
    }

    private void AmountRangeCanvas_MouseMove(object sender, MouseEventArgs e)
    {
        if (_amountDragTarget == AmountDragTarget.None || !_amountRangeCanvasHasCapture())
        {
            return;
        }

        SetSelectedAmount(_amountDragTarget, AmountFromCanvasX(e.GetPosition(AmountRangeCanvas).X), updateTextBoxes: true);
    }

    private void AmountRangeCanvas_MouseLeftButtonUp(object sender, MouseButtonEventArgs e)
    {
        _amountDragTarget = AmountDragTarget.None;
        AmountRangeCanvas.ReleaseMouseCapture();
    }

    private void AmountTextBox_TextChanged(object sender, TextChangedEventArgs e)
    {
        if (_isUpdatingAmountControls || AmountRangeCanvas is null)
        {
            return;
        }

        _isUpdatingAmountControls = true;

        if (TryParseNullableDecimal(MinPriceTextBox.Text, out var minPrice) && minPrice.HasValue)
        {
            _selectedMinAmount = ClampToAmountRange(minPrice.Value);
        }

        if (TryParseNullableDecimal(MaxPriceTextBox.Text, out var maxPrice) && maxPrice.HasValue)
        {
            _selectedMaxAmount = ClampToAmountRange(maxPrice.Value);
        }

        if (_selectedMinAmount > _selectedMaxAmount)
        {
            if (ReferenceEquals(sender, MinPriceTextBox))
            {
                _selectedMaxAmount = _selectedMinAmount;
            }
            else
            {
                _selectedMinAmount = _selectedMaxAmount;
            }
        }

        UpdateAmountSliderLabels();
        UpdateAmountRangeVisual();
        _isUpdatingAmountControls = false;
    }

    private void SetSelectedAmount(AmountDragTarget target, decimal value, bool updateTextBoxes)
    {
        value = ClampToAmountRange(value);

        if (target == AmountDragTarget.Minimum)
        {
            _selectedMinAmount = Math.Min(value, _selectedMaxAmount);
        }
        else if (target == AmountDragTarget.Maximum)
        {
            _selectedMaxAmount = Math.Max(value, _selectedMinAmount);
        }

        _isUpdatingAmountControls = true;
        if (updateTextBoxes)
        {
            MinPriceTextBox.Text = FormatMoney(_selectedMinAmount);
            MaxPriceTextBox.Text = FormatMoney(_selectedMaxAmount);
        }

        UpdateAmountSliderLabels();
        UpdateAmountRangeVisual();
        _isUpdatingAmountControls = false;
    }

    private decimal ClampToAmountRange(decimal value)
    {
        return Math.Min(_amountSliderMaximum, Math.Max(_amountSliderMinimum, value));
    }

    private void UpdateAmountSliderLabels()
    {
        MinAmountSliderValueTextBlock.Text = FormatMoney(_selectedMinAmount);
        MaxAmountSliderValueTextBlock.Text = FormatMoney(_selectedMaxAmount);
    }

    private void AmountRangeCanvas_SizeChanged(object sender, SizeChangedEventArgs e)
    {
        UpdateAmountRangeVisual();
    }

    private void UpdateAmountRangeVisual()
    {
        if (AmountRangeCanvas is null || AmountTrackBorder is null || AmountSelectedRangeBorder is null)
        {
            return;
        }

        var canvasWidth = AmountRangeCanvas.ActualWidth;
        if (canvasWidth <= 22)
        {
            return;
        }

        const double thumbSize = 20;
        var trackLeft = thumbSize / 2;
        var trackTop = 15d;
        var trackWidth = Math.Max(1, canvasWidth - thumbSize);

        AmountTrackBorder.Width = trackWidth;
        Canvas.SetLeft(AmountTrackBorder, trackLeft);
        Canvas.SetTop(AmountTrackBorder, trackTop);

        var minX = AmountToCanvasX(_selectedMinAmount, trackLeft, trackWidth);
        var maxX = AmountToCanvasX(_selectedMaxAmount, trackLeft, trackWidth);

        AmountSelectedRangeBorder.Width = Math.Max(0, maxX - minX);
        Canvas.SetLeft(AmountSelectedRangeBorder, minX);
        Canvas.SetTop(AmountSelectedRangeBorder, trackTop);

        Canvas.SetLeft(MinAmountThumb, minX - thumbSize / 2);
        Canvas.SetLeft(MaxAmountThumb, maxX - thumbSize / 2);
    }

    private double AmountToCanvasX(decimal value, double trackLeft, double trackWidth)
    {
        var range = _amountSliderMaximum - _amountSliderMinimum;
        if (range <= 0)
        {
            return trackLeft;
        }

        var ratio = (double)((value - _amountSliderMinimum) / range);
        return trackLeft + ratio * trackWidth;
    }

    private decimal AmountFromCanvasX(double x)
    {
        const double thumbSize = 20;
        var trackLeft = thumbSize / 2;
        var trackWidth = Math.Max(1, AmountRangeCanvas.ActualWidth - thumbSize);
        var ratio = Math.Min(1d, Math.Max(0d, (x - trackLeft) / trackWidth));
        return _amountSliderMinimum + (_amountSliderMaximum - _amountSliderMinimum) * (decimal)ratio;
    }

    private bool _amountRangeCanvasHasCapture()
    {
        return Mouse.Captured == AmountRangeCanvas;
    }

    private void RenderBarChart(Panel panel, IReadOnlyList<DashboardSeriesPoint> points, Brush accentBrush, string emptyMessageKey)
    {
        panel.Children.Clear();

        if (points.Count == 0)
        {
            panel.Children.Add(CreateEmptyState(LanguageManager.Get(emptyMessageKey)));
            return;
        }

        var maxValue = points.Max(point => point.Value);
        if (maxValue <= 0)
        {
            maxValue = 1;
        }

        var barMaxWidth = Math.Max(120, panel.ActualWidth - 240);
        if (double.IsNaN(barMaxWidth) || double.IsInfinity(barMaxWidth))
        {
            barMaxWidth = 180;
        }

        foreach (var point in points)
        {
            var row = new Grid
            {
                Margin = new Thickness(0, 0, 0, 12)
            };

            row.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(135) });
            row.ColumnDefinitions.Add(new ColumnDefinition());
            row.ColumnDefinitions.Add(new ColumnDefinition { Width = GridLength.Auto });

            var label = new TextBlock
            {
                Text = point.Label,
                VerticalAlignment = VerticalAlignment.Center,
                TextTrimming = TextTrimming.CharacterEllipsis,
                Margin = new Thickness(0, 0, 12, 0)
            };

            var barTrack = new Border
            {
                Height = 18,
                CornerRadius = new CornerRadius(9),
                Background = new SolidColorBrush(Color.FromRgb(255, 231, 238)),
                VerticalAlignment = VerticalAlignment.Center
            };

            var barFill = new Border
            {
                Height = 18,
                Width = barMaxWidth * (double)(point.Value / maxValue),
                CornerRadius = new CornerRadius(9),
                Background = accentBrush,
                HorizontalAlignment = HorizontalAlignment.Left
            };

            var barGrid = new Grid();
            barGrid.Children.Add(barTrack);
            barGrid.Children.Add(barFill);

            var value = new TextBlock
            {
                Text = FormatMoney(point.Value),
                Margin = new Thickness(12, 0, 0, 0),
                VerticalAlignment = VerticalAlignment.Center,
                FontWeight = FontWeights.SemiBold,
                MinWidth = 72,
                TextAlignment = TextAlignment.Right
            };

            Grid.SetColumn(label, 0);
            Grid.SetColumn(barGrid, 1);
            Grid.SetColumn(value, 2);

            row.Children.Add(label);
            row.Children.Add(barGrid);
            row.Children.Add(value);

            panel.Children.Add(row);
        }
    }

    private void RenderStatusPieChart(IReadOnlyList<DashboardSeriesPoint> points)
    {
        StatusPieCanvas.Children.Clear();
        StatusLegendPanel.Children.Clear();

        if (points.Count == 0)
        {
            StatusLegendPanel.Children.Add(CreateEmptyState(LanguageManager.Get("DashboardNoStatusData")));
            return;
        }

        var total = points.Sum(point => point.Value);
        if (total <= 0)
        {
            StatusLegendPanel.Children.Add(CreateEmptyState(LanguageManager.Get("DashboardNoStatusData")));
            return;
        }

        const double size = 220;
        const double radius = size / 2;
        var center = new Point(radius, radius);
        double startAngle = 0;

        StatusPieCanvas.Children.Add(new Ellipse
        {
            Width = size,
            Height = size,
            Fill = new SolidColorBrush(Color.FromRgb(255, 251, 246))
        });

        for (var index = 0; index < points.Count; index++)
        {
            var point = points[index];
            var sweepAngle = 360d * (double)(point.Value / total);
            var slice = CreatePieSlice(center, radius, startAngle, sweepAngle, ChartBrushes[index % ChartBrushes.Length]);
            StatusPieCanvas.Children.Add(slice);

            var percentage = point.Value / total;
            var legendRow = new StackPanel
            {
                Orientation = Orientation.Horizontal,
                Margin = new Thickness(0, 0, 0, 10)
            };

            legendRow.Children.Add(new Border
            {
                Width = 14,
                Height = 14,
                CornerRadius = new CornerRadius(7),
                Background = ChartBrushes[index % ChartBrushes.Length],
                Margin = new Thickness(0, 2, 10, 0)
            });

            legendRow.Children.Add(new TextBlock
            {
                Text = $"{FormatStatusLabel(point.Label)} ({percentage:P0})",
                FontWeight = FontWeights.SemiBold
            });

            legendRow.Children.Add(new TextBlock
            {
                Margin = new Thickness(8, 0, 0, 0),
                Text = $"{LanguageManager.Get("DashboardOrdersShort")}: {point.Value:N0}",
                Foreground = (Brush)FindResource("MutedTextBrush")
            });

            StatusLegendPanel.Children.Add(legendRow);
            startAngle += sweepAngle;
        }

        StatusPieCanvas.Children.Add(new Ellipse
        {
            Width = 84,
            Height = 84,
            Fill = Brushes.White,
            Stroke = new SolidColorBrush(Color.FromRgb(232, 222, 212)),
            StrokeThickness = 1.5
        });
        Canvas.SetLeft(StatusPieCanvas.Children[^1], 68);
        Canvas.SetTop(StatusPieCanvas.Children[^1], 68);

        var totalText = new TextBlock
        {
            Width = 84,
            TextAlignment = TextAlignment.Center,
            FontWeight = FontWeights.Bold,
            FontSize = 12,
            Foreground = (Brush)FindResource("TextBrush"),
            Text = $"{LanguageManager.Get("DashboardOrdersShort")}\n{total:N0}"
        };
        StatusPieCanvas.Children.Add(totalText);
        Canvas.SetLeft(totalText, 68);
        Canvas.SetTop(totalText, 94);
    }

    private void RenderTimelineChart(IReadOnlyList<DashboardSeriesPoint> points)
    {
        TimelineChartCanvas.Children.Clear();

        if (points.Count == 0)
        {
            TimelineChartCanvas.Children.Add(CreateCanvasPlaceholder(LanguageManager.Get("DashboardNoTimelineData")));
            return;
        }

        var width = Math.Max(TimelineChartCanvas.ActualWidth, 520);
        var height = Math.Max(TimelineChartCanvas.ActualHeight, 240);
        const double left = 48;
        const double top = 18;
        const double bottom = 36;
        const double right = 18;
        var plotWidth = width - left - right;
        var plotHeight = height - top - bottom;

        var maxValue = points.Max(point => point.Value);
        if (maxValue <= 0)
        {
            maxValue = 1;
        }

        for (var guideIndex = 0; guideIndex < 4; guideIndex++)
        {
            var guideY = top + (plotHeight / 3 * guideIndex);
            TimelineChartCanvas.Children.Add(new Line
            {
                X1 = left,
                Y1 = guideY,
                X2 = left + plotWidth,
                Y2 = guideY,
                Stroke = new SolidColorBrush(Color.FromRgb(232, 222, 212)),
                StrokeThickness = 1
            });
        }

        TimelineChartCanvas.Children.Add(new Line
        {
            X1 = left,
            Y1 = top,
            X2 = left,
            Y2 = top + plotHeight,
            Stroke = new SolidColorBrush(Color.FromRgb(218, 205, 193)),
            StrokeThickness = 1
        });

        TimelineChartCanvas.Children.Add(new Line
        {
            X1 = left,
            Y1 = top + plotHeight,
            X2 = left + plotWidth,
            Y2 = top + plotHeight,
            Stroke = new SolidColorBrush(Color.FromRgb(218, 205, 193)),
            StrokeThickness = 1
        });

        var polyline = new Polyline
        {
            Stroke = ChartBrushes[2],
            StrokeThickness = 3
        };

        for (var index = 0; index < points.Count; index++)
        {
            var x = left + (points.Count == 1 ? plotWidth / 2 : index * (plotWidth / (points.Count - 1)));
            var ratio = (double)(points[index].Value / maxValue);
            var y = top + plotHeight - (plotHeight * ratio);

            polyline.Points.Add(new Point(x, y));

            var dot = new Ellipse
            {
                Width = 10,
                Height = 10,
                Fill = ChartBrushes[0],
                Stroke = Brushes.White,
                StrokeThickness = 2
            };

            TimelineChartCanvas.Children.Add(dot);
            Canvas.SetLeft(dot, x - 5);
            Canvas.SetTop(dot, y - 5);

            if (index == 0 || index == points.Count - 1 || points.Count <= 6 || index % 2 == 0)
            {
                var label = new TextBlock
                {
                    Text = points[index].Label,
                    FontSize = 11,
                    Foreground = (Brush)FindResource("MutedTextBrush")
                };
                TimelineChartCanvas.Children.Add(label);
                Canvas.SetLeft(label, Math.Max(0, x - 16));
                Canvas.SetTop(label, top + plotHeight + 6);
            }
        }

        var maxLabel = new TextBlock
        {
            Text = FormatMoney(maxValue),
            FontSize = 11,
            Foreground = (Brush)FindResource("MutedTextBrush")
        };

        TimelineChartCanvas.Children.Add(maxLabel);
        Canvas.SetLeft(maxLabel, 0);
        Canvas.SetTop(maxLabel, top - 8);
        TimelineChartCanvas.Children.Add(polyline);
    }

    private void RenderMonthHistogram(IReadOnlyList<DashboardSeriesPoint> points)
    {
        MonthHistogramCanvas.Children.Clear();

        if (points.Count == 0)
        {
            MonthHistogramCanvas.Children.Add(CreateCanvasPlaceholder(LanguageManager.Get("DashboardNoMonthData")));
            return;
        }

        var requiredWidth = Math.Max(420, points.Count * 86 + 78);
        var width = Math.Max(MonthHistogramCanvas.ActualWidth, requiredWidth);
        var height = Math.Max(MonthHistogramCanvas.ActualHeight, 210);
        MonthHistogramCanvas.Width = width;

        const double left = 54;
        const double top = 20;
        const double bottom = 42;
        const double right = 18;
        var plotWidth = width - left - right;
        var plotHeight = height - top - bottom;

        var maxValue = points.Max(point => point.Value);
        if (maxValue <= 0)
        {
            maxValue = 1;
        }

        for (var guideIndex = 0; guideIndex < 4; guideIndex++)
        {
            var guideY = top + (plotHeight / 3 * guideIndex);
            MonthHistogramCanvas.Children.Add(new Line
            {
                X1 = left,
                Y1 = guideY,
                X2 = left + plotWidth,
                Y2 = guideY,
                Stroke = new SolidColorBrush(Color.FromRgb(232, 222, 212)),
                StrokeThickness = 1
            });
        }

        MonthHistogramCanvas.Children.Add(new Line
        {
            X1 = left,
            Y1 = top,
            X2 = left,
            Y2 = top + plotHeight,
            Stroke = new SolidColorBrush(Color.FromRgb(218, 205, 193)),
            StrokeThickness = 1
        });

        MonthHistogramCanvas.Children.Add(new Line
        {
            X1 = left,
            Y1 = top + plotHeight,
            X2 = left + plotWidth,
            Y2 = top + plotHeight,
            Stroke = new SolidColorBrush(Color.FromRgb(218, 205, 193)),
            StrokeThickness = 1
        });

        var maxLabel = new TextBlock
        {
            Text = FormatMoney(maxValue),
            FontSize = 11,
            Foreground = (Brush)FindResource("MutedTextBrush")
        };
        MonthHistogramCanvas.Children.Add(maxLabel);
        Canvas.SetLeft(maxLabel, 0);
        Canvas.SetTop(maxLabel, top - 8);

        var slotWidth = plotWidth / points.Count;
        var barWidth = Math.Min(54, Math.Max(30, slotWidth * 0.58));

        for (var index = 0; index < points.Count; index++)
        {
            var point = points[index];
            var ratio = (double)(point.Value / maxValue);
            var barHeight = Math.Max(4, plotHeight * ratio);
            var x = left + index * slotWidth + (slotWidth - barWidth) / 2;
            var y = top + plotHeight - barHeight;

            var bar = new Rectangle
            {
                Width = barWidth,
                Height = barHeight,
                RadiusX = 4,
                RadiusY = 4,
                Fill = ChartBrushes[index % ChartBrushes.Length]
            };
            MonthHistogramCanvas.Children.Add(bar);
            Canvas.SetLeft(bar, x);
            Canvas.SetTop(bar, y);

            var valueLabel = new TextBlock
            {
                Text = FormatMoney(point.Value),
                FontSize = 11,
                FontWeight = FontWeights.SemiBold,
                Foreground = (Brush)FindResource("TextBrush")
            };
            MonthHistogramCanvas.Children.Add(valueLabel);
            Canvas.SetLeft(valueLabel, Math.Max(left, x - 14));
            Canvas.SetTop(valueLabel, Math.Max(0, y - 22));

            var monthLabel = new TextBlock
            {
                Text = point.Label,
                FontSize = 11,
                Foreground = (Brush)FindResource("MutedTextBrush")
            };
            MonthHistogramCanvas.Children.Add(monthLabel);
            Canvas.SetLeft(monthLabel, x - 2);
            Canvas.SetTop(monthLabel, top + plotHeight + 10);
        }
    }

    private static Path CreatePieSlice(Point center, double radius, double startAngle, double sweepAngle, Brush fill)
    {
        var startRadians = Math.PI * startAngle / 180.0;
        var endRadians = Math.PI * (startAngle + sweepAngle) / 180.0;

        var startPoint = new Point(
            center.X + radius * Math.Cos(startRadians),
            center.Y + radius * Math.Sin(startRadians));

        var endPoint = new Point(
            center.X + radius * Math.Cos(endRadians),
            center.Y + radius * Math.Sin(endRadians));

        var geometry = new PathGeometry();
        var figure = new PathFigure
        {
            StartPoint = center,
            IsClosed = true
        };

        figure.Segments.Add(new LineSegment(startPoint, true));
        figure.Segments.Add(new ArcSegment(
            endPoint,
            new Size(radius, radius),
            0,
            sweepAngle > 180,
            SweepDirection.Clockwise,
            true));
        geometry.Figures.Add(figure);

        return new Path
        {
            Data = geometry,
            Fill = fill,
            Stroke = Brushes.White,
            StrokeThickness = 2
        };
    }

    private static TextBlock CreateEmptyState(string text)
    {
        return new TextBlock
        {
            Text = text,
            Foreground = new SolidColorBrush(Color.FromRgb(123, 129, 122)),
            FontStyle = FontStyles.Italic
        };
    }

    private static TextBlock CreateCanvasPlaceholder(string text)
    {
        return new TextBlock
        {
            Text = text,
            Foreground = new SolidColorBrush(Color.FromRgb(123, 129, 122)),
            FontStyle = FontStyles.Italic,
            Margin = new Thickness(12)
        };
    }

    private void DashboardDataGrid_AutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
    {
        e.Column.Header = LanguageManager.GetColumnName(e.PropertyName) ?? e.PropertyName;

        if (e.PropertyName.Equals("order_id", StringComparison.OrdinalIgnoreCase))
        {
            e.Column.Header = LanguageManager.CurrentLanguage == AppLanguage.Russian ? "Номер заказа" : "Order Number";
        }

        if (e.PropertyName.Equals("order_items", StringComparison.OrdinalIgnoreCase))
        {
            e.Cancel = true;
            return;
        }

        if (e.PropertyName.Equals("start_date", StringComparison.OrdinalIgnoreCase) ||
            e.PropertyName.Equals("end_date", StringComparison.OrdinalIgnoreCase))
        {
            if (e.Column is DataGridTextColumn textColumn)
            {
                textColumn.Binding.StringFormat = "dd.MM.yyyy";
            }
        }

        if (e.PropertyName.Equals("total_cost", StringComparison.OrdinalIgnoreCase) ||
            e.PropertyName.Equals("line_total", StringComparison.OrdinalIgnoreCase) ||
            e.PropertyName.Equals("price_per_m", StringComparison.OrdinalIgnoreCase) ||
            e.PropertyName.Equals("fabric_amount", StringComparison.OrdinalIgnoreCase))
        {
            if (e.Column is DataGridTextColumn numericColumn)
            {
                numericColumn.Binding.StringFormat = "N2";
            }
        }
    }

    private void DashboardDataGrid_AutoGeneratedColumns(object? sender, EventArgs e)
    {
        if (sender is DataGrid dataGrid)
        {
            EnsureDashboardOrderDetailsButtonColumn(dataGrid);
        }
    }

    private void EnsureDashboardOrderDetailsButtonColumn(DataGrid dataGrid)
    {
        var existingColumn = dataGrid.Columns.FirstOrDefault(column =>
            string.Equals(column.SortMemberPath, DashboardOrderDetailsColumnSortKey, StringComparison.OrdinalIgnoreCase));

        if (existingColumn is not null)
        {
            dataGrid.Columns.Remove(existingColumn);
        }

        if (!dataGrid.Columns.Any(column =>
                string.Equals(column.SortMemberPath, "order_id", StringComparison.OrdinalIgnoreCase)))
        {
            return;
        }

        var iconPathFactory = new FrameworkElementFactory(typeof(Path));
        iconPathFactory.SetValue(Path.WidthProperty, 14d);
        iconPathFactory.SetValue(Path.HeightProperty, 16d);
        iconPathFactory.SetValue(Path.StretchProperty, Stretch.Uniform);
        iconPathFactory.SetValue(Path.StrokeProperty, (Brush)FindResource("AccentBrush"));
        iconPathFactory.SetValue(Path.FillProperty, Brushes.Transparent);
        iconPathFactory.SetValue(Path.StrokeThicknessProperty, 1.6d);
        iconPathFactory.SetValue(Path.StrokeStartLineCapProperty, PenLineCap.Round);
        iconPathFactory.SetValue(Path.StrokeEndLineCapProperty, PenLineCap.Round);
        iconPathFactory.SetValue(Path.StrokeLineJoinProperty, PenLineJoin.Round);
        iconPathFactory.SetValue(Path.DataProperty, Geometry.Parse("M4,1.5 L10.5,1.5 L14,5 L14,14.5 L4,14.5 Z M10.5,1.5 L10.5,5 L14,5 M6.5,7.5 L11.5,7.5 M6.5,10.5 L11.5,10.5"));

        var viewboxFactory = new FrameworkElementFactory(typeof(Viewbox));
        viewboxFactory.SetValue(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Center);
        viewboxFactory.SetValue(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center);
        viewboxFactory.AppendChild(iconPathFactory);

        var buttonFactory = new FrameworkElementFactory(typeof(Button));
        buttonFactory.SetValue(FrameworkElement.WidthProperty, 38d);
        buttonFactory.SetValue(FrameworkElement.HeightProperty, 38d);
        buttonFactory.SetValue(FrameworkElement.MarginProperty, new Thickness(0));
        buttonFactory.SetValue(Control.PaddingProperty, new Thickness(0));
        buttonFactory.SetValue(Control.CursorProperty, Cursors.Hand);
        buttonFactory.SetValue(Control.ForegroundProperty, (Brush)FindResource("AccentBrush"));
        buttonFactory.SetValue(Control.BackgroundProperty, Brushes.Transparent);
        buttonFactory.SetValue(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Center);
        buttonFactory.SetValue(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center);
        buttonFactory.SetValue(FrameworkElement.ToolTipProperty, LanguageManager.CurrentLanguage == AppLanguage.Russian ? "Детали" : "Details");
        buttonFactory.SetValue(Control.TemplateProperty, BuildDashboardOrderDetailsButtonTemplate());
        buttonFactory.SetBinding(FrameworkElement.TagProperty, new System.Windows.Data.Binding("order_id"));
        buttonFactory.AddHandler(Button.ClickEvent, new RoutedEventHandler(DashboardOrderDetailsButton_Click));
        buttonFactory.AppendChild(viewboxFactory);

        dataGrid.Columns.Add(new DataGridTemplateColumn
        {
            Header = LanguageManager.CurrentLanguage == AppLanguage.Russian ? "Детали" : "Details",
            Width = new DataGridLength(88),
            SortMemberPath = DashboardOrderDetailsColumnSortKey,
            IsReadOnly = true,
            CellTemplate = new DataTemplate
            {
                VisualTree = buttonFactory
            }
        });

        if (dataGrid.Columns.Count > 0)
        {
            dataGrid.Columns[^1].DisplayIndex = dataGrid.Columns.Count - 1;
        }
    }

    private static ControlTemplate BuildDashboardOrderDetailsButtonTemplate()
    {
        var borderFactory = new FrameworkElementFactory(typeof(Border));
        borderFactory.Name = "RootBorder";
        borderFactory.SetValue(Border.BackgroundProperty, Brushes.Transparent);
        borderFactory.SetValue(Border.BorderBrushProperty, Brushes.Transparent);
        borderFactory.SetValue(Border.BorderThicknessProperty, new Thickness(0));
        borderFactory.SetValue(Border.CornerRadiusProperty, new CornerRadius(0));

        var presenterFactory = new FrameworkElementFactory(typeof(ContentPresenter));
        presenterFactory.SetValue(HorizontalAlignmentProperty, HorizontalAlignment.Center);
        presenterFactory.SetValue(VerticalAlignmentProperty, VerticalAlignment.Center);
        borderFactory.AppendChild(presenterFactory);

        var template = new ControlTemplate(typeof(Button))
        {
            VisualTree = borderFactory
        };

        var hoverTrigger = new Trigger
        {
            Property = UIElement.IsMouseOverProperty,
            Value = true
        };
        hoverTrigger.Setters.Add(new Setter(UIElement.OpacityProperty, 0.84d, "RootBorder"));

        var pressedTrigger = new Trigger
        {
            Property = ButtonBase.IsPressedProperty,
            Value = true
        };
        pressedTrigger.Setters.Add(new Setter(UIElement.OpacityProperty, 0.68d, "RootBorder"));

        template.Triggers.Add(hoverTrigger);
        template.Triggers.Add(pressedTrigger);
        return template;
    }

    private void DashboardOrderDetailsButton_Click(object sender, RoutedEventArgs e)
    {
        if (_isBusy || sender is not Button button)
        {
            return;
        }

        var rawOrderId = button.Tag;
        if (rawOrderId is null || rawOrderId is DBNull)
        {
            MessageBox.Show(
                LanguageManager.CurrentLanguage == AppLanguage.Russian ? "Не удалось определить ID заказа." : "Could not determine the order ID.",
                Title,
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
            return;
        }

        if (button.DataContext is DataRowView rowView)
        {
            DashboardDataGrid.SelectedItem = rowView;
        }

        var orderDetailsWindow = new OrderDetailsWindow(Convert.ToInt32(rawOrderId, CultureInfo.CurrentCulture))
        {
            Owner = this
        };

        orderDetailsWindow.ShowDialog();
    }

    private async void ApplyFiltersButton_Click(object sender, RoutedEventArgs e)
    {
        if (_isBusy)
        {
            return;
        }

        SetBusyState(true);
        try
        {
            await LoadDashboardAsync();
        }
        catch (Exception exception)
        {
            MessageBox.Show(exception.Message, LanguageManager.Get("Dashboard"), MessageBoxButton.OK, MessageBoxImage.Error);
        }
        finally
        {
            SetBusyState(false);
        }
    }

    private async void ResetFiltersButton_Click(object sender, RoutedEventArgs e)
    {
        if (_isBusy)
        {
            return;
        }

        ClientComboBox.SelectedIndex = 0;
        StatusComboBox.SelectedIndex = 0;
        ProductComboBox.SelectedIndex = 0;
        FabricTypeComboBox.SelectedIndex = 0;
        DateFromPicker.SelectedDate = null;
        DateToPicker.SelectedDate = null;
        ResetAmountFilterControls();

        SetBusyState(true);
        try
        {
            await LoadDashboardAsync();
        }
        catch (Exception exception)
        {
            MessageBox.Show(exception.Message, LanguageManager.Get("Dashboard"), MessageBoxButton.OK, MessageBoxImage.Error);
        }
        finally
        {
            SetBusyState(false);
        }
    }

    private void ApplyLocalization()
    {
        Title = LanguageManager.Get("Dashboard");
        DashboardTitleTextBlock.Text = LanguageManager.Get("Dashboard");
        DashboardSubtitleTextBlock.Text = LanguageManager.Get("DashboardSubtitle");
        FiltersHeaderTextBlock.Text = LanguageManager.Get("DashboardFilters");
        ClientFilterLabelTextBlock.Text = LanguageManager.Get("DashboardClient");
        StatusFilterLabelTextBlock.Text = LanguageManager.Get("DashboardStatus");
        ProductFilterLabelTextBlock.Text = LanguageManager.Get("DashboardProduct");
        FabricFilterLabelTextBlock.Text = LanguageManager.Get("DashboardFabricType");
        DateFromLabelTextBlock.Text = LanguageManager.Get("DashboardDateFrom");
        DateToLabelTextBlock.Text = LanguageManager.Get("DashboardDateTo");
        AmountRangeLabelTextBlock.Text = LanguageManager.Get("DashboardAmountRange");
        MinPriceLabelTextBlock.Text = LanguageManager.Get("DashboardMinAmount");
        MaxPriceLabelTextBlock.Text = LanguageManager.Get("DashboardMaxAmount");
        ApplyFiltersButton.Content = LanguageManager.Get("DashboardApply");
        ResetFiltersButton.Content = LanguageManager.Get("DashboardReset");
        TotalRevenueLabelTextBlock.Text = LanguageManager.Get("DashboardTotalSum");
        OrdersCountLabelTextBlock.Text = LanguageManager.Get("DashboardOrderCount");
        AverageCheckLabelTextBlock.Text = LanguageManager.Get("DashboardAverage");
        RangeLabelTextBlock.Text = LanguageManager.Get("DashboardRange");
        DataGridHeaderTextBlock.Text = LanguageManager.Get("DashboardDataGrid");
        StatusChartHeaderTextBlock.Text = LanguageManager.Get("DashboardStatusChart");
        TimelineChartHeaderTextBlock.Text = LanguageManager.Get("DashboardTimelineChart");
        ProductChartHeaderTextBlock.Text = LanguageManager.Get("DashboardCategoryChart");
        MonthChartHeaderTextBlock.Text = LanguageManager.Get("DashboardMonthChart");
        RefreshFilterItems();
        var hasStatusFilter = !string.IsNullOrWhiteSpace(ReadSelectedValue(StatusComboBox));
        UpdateChartLayout(hasStatusFilter);
        if (!hasStatusFilter)
        {
            RenderStatusPieChart(_statusPoints);
        }
        else
        {
            StatusPieCanvas.Children.Clear();
            StatusLegendPanel.Children.Clear();
        }

        RenderBarChart(ProductChartPanel, _categoryPoints, ChartBrushes[0], "DashboardNoCategoryData");
        RenderTimelineChart(_timelinePoints);
        RenderMonthHistogram(_monthPoints);
    }

    private void SetBusyState(bool isBusy)
    {
        _isBusy = isBusy;
        ApplyFiltersButton.IsEnabled = !isBusy;
        ResetFiltersButton.IsEnabled = !isBusy;
        AmountRangeCanvas.IsEnabled = !isBusy;
        Mouse.OverrideCursor = isBusy ? System.Windows.Input.Cursors.Wait : null;
        DashboardStatusTextBlock.Text = isBusy ? LanguageManager.Get("DashboardLoading") : DashboardStatusTextBlock.Text;
    }

    private void DashboardWindow_SizeChanged(object sender, SizeChangedEventArgs e)
    {
        if (!IsLoaded)
        {
            return;
        }

        RenderTimelineChart(_timelinePoints);
        RenderMonthHistogram(_monthPoints);
    }

    private void LanguageManager_LanguageChanged(object? sender, EventArgs e)
    {
        ApplyLocalization();
    }

    private List<LookupOption> BuildOptionsWithAll(IEnumerable<LookupOption> options, string allKey)
    {
        return
        [
            new LookupOption { Value = string.Empty, Label = LanguageManager.Get(allKey) },
            .. options
        ];
    }

    private List<LookupOption> BuildStatusOptions()
    {
        return
        [
            new LookupOption { Value = string.Empty, Label = LanguageManager.Get("AllStatuses") },
            new LookupOption { Value = "Pending", Label = LanguageManager.Get("StatusPending") },
            new LookupOption { Value = "Shipped", Label = LanguageManager.Get("StatusShipped") },
            new LookupOption { Value = "Completed", Label = LanguageManager.Get("StatusCompleted") }
        ];
    }

    private static string FormatMoney(decimal value)
    {
        return value.ToString("N2", CultureInfo.CurrentCulture);
    }

    private void ResetAmountFilterControls()
    {
        _isUpdatingAmountControls = true;
        _selectedMinAmount = _amountSliderMinimum;
        _selectedMaxAmount = _amountSliderMaximum;
        MinPriceTextBox.Text = FormatMoney(_amountSliderMinimum);
        MaxPriceTextBox.Text = FormatMoney(_amountSliderMaximum);
        UpdateAmountSliderLabels();
        UpdateAmountRangeVisual();
        _isUpdatingAmountControls = false;
    }

    private static string FormatStatusLabel(string status)
    {
        return status switch
        {
            "Pending" => LanguageManager.Get("StatusPending"),
            "Shipped" => LanguageManager.Get("StatusShipped"),
            "Completed" => LanguageManager.Get("StatusCompleted"),
            _ => status
        };
    }

    private void UpdateChartLayout(bool hideStatusChart)
    {
        StatusChartContainer.Visibility = hideStatusChart ? Visibility.Collapsed : Visibility.Visible;
        Grid.SetRow(RightChartsGrid, hideStatusChart ? 0 : 1);
        Grid.SetRowSpan(RightChartsGrid, hideStatusChart ? 2 : 1);
    }

    protected override void OnClosed(EventArgs e)
    {
        LanguageManager.LanguageChanged -= LanguageManager_LanguageChanged;
        base.OnClosed(e);
    }
}
