using System.Data;
using System.Globalization;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Threading;
using BabyShop.Configuration;
using BabyShop.Infrastructure;
using BabyShop.Localization;
using BabyShop.Models;
using BabyShop.Reporting;
using BabyShop.Repositories;
using BabyShop.Services;

namespace BabyShop;

public partial class MainWindow : Window
{
    private const string ManageUsersPermission = "MANAGE_USERS";
    private const string OrderDetailsColumnSortKey = "__order_details_action";
    private static readonly TimeSpan AutoProjectBackupCheckInterval = TimeSpan.FromHours(1);
    private readonly AppUser _currentUser;
    private readonly BabyShopRepository _repository;
    private readonly BackupService _backupService;
    private bool _isBusy;
    private bool _autoProjectBackupInProgress;
    private bool _languageSelectorReady;
    private int _selectedTabIndex;
    private DateTime? _lastRefreshAt;
    private DispatcherTimer? _autoProjectBackupTimer;

    private DataView? _customerView;
    private DataView? _fabricView;
    private DataView? _productView;
    private DataView? _orderView;
    private DataView? _orderProductView;

    public MainWindow(AppUser currentUser)
    {
        InitializeComponent();
        WindowStartupLocation = WindowStartupLocation.CenterScreen;
        WindowAppearance.ApplySharedIcon(this);
        _currentUser = currentUser;
        _repository = new BabyShopRepository(new DbHelper(DatabaseSettings.BuildConnectionString()));
        _backupService = new BackupService(_repository, _currentUser);

        foreach (var grid in new[] { CustomerGrid, FabricGrid, ProductGrid, CustomerOrderGrid, OrderProductGrid })
        {
            grid.AutoGeneratingColumn += DataGrid_AutoGeneratingColumn;
            grid.AutoGeneratingColumn += DataGrid_ImageAutoGeneratingColumn;
            grid.MouseDoubleClick += DataGrid_MouseDoubleClick;
            grid.PreviewMouseRightButtonUp += DataGrid_PreviewMouseRightButtonUp;
        }

        CustomerOrderGrid.AutoGeneratingColumn += CustomerOrderGrid_AutoGeneratingColumn;
        CustomerOrderGrid.AutoGeneratedColumns += CustomerOrderGrid_AutoGeneratedColumns;

        ProductGrid.RowHeight = 74;

        _languageSelectorReady = true;

        ApplyLocalization();
    }

    private async void Window_Loaded(object sender, RoutedEventArgs e)
    {
        await InitializeAsync();
    }

    private async Task InitializeAsync()
    {
        SetBusyState(true);

        try
        {
            await _repository.TestConnectionAsync();
            StatusTextBlock.Text = LanguageManager.Get("ConnectedToMySql");
            StatusDot.Fill = (Brush)FindResource("SuccessBrush");
            await LoadAllTablesAsync();
            await EnsureAutomaticProjectBackupAsync();
            StartAutomaticProjectBackupScheduler();
        }
        catch (Exception exception)
        {
            StatusTextBlock.Text = LanguageManager.Get("ConnectionFailed");
            StatusDot.Fill = (Brush)FindResource("WarningBrush");
            MessageBox.Show(exception.Message, LanguageManager.Get("DatabaseConnection"), MessageBoxButton.OK, MessageBoxImage.Error);
        }
        finally
        {
            SetBusyState(false);
        }
    }

    private async Task LoadAllTablesAsync()
    {
        _customerView = await LoadTableIntoGridAsync("CUSTOMERVIEW", CustomerGrid, CustomerCountTextBlock);
        _fabricView = await LoadTableIntoGridAsync("FABRICVIEW", FabricGrid, FabricCountTextBlock);
        _productView = await LoadTableIntoGridAsync("PRODUCTFABRICVIEW", ProductGrid, ProductCountTextBlock);
        _orderView = await LoadTableIntoGridAsync("CUSTOMERORDERSVIEW", CustomerOrderGrid, OrderCountTextBlock);
        _orderProductView = await LoadTableIntoGridAsync("ORDERPRODUCTVIEW", OrderProductGrid, OrderProductCountTextBlock);

        _lastRefreshAt = DateTime.Now;
        LastRefreshTextBlock.Text = LanguageManager.Format("LastRefreshed", _lastRefreshAt.Value.ToString("g"));
        FooterMessageTextBlock.Text = LanguageManager.Get("AllTablesSynced");

        ApplySearch(SearchBox.Text);
    }

    private async Task<DataView?> LoadTableIntoGridAsync(string tableName, DataGrid dataGrid, TextBlock countTextBlock)
    {
        try
        {
            var table = await _repository.GetDisplayTableAsync(tableName);
            var view = table.DefaultView;
            ApplyDefaultGridSort(tableName, view);
            dataGrid.ItemsSource = view;
            if (tableName.Equals("CUSTOMERORDERSVIEW", StringComparison.OrdinalIgnoreCase))
            {
                EnsureOrderDetailsButtonColumn(dataGrid);
            }
            countTextBlock.Text = table.Rows.Count.ToString();
            return view;
        }
        catch (Exception exception)
        {
            dataGrid.ItemsSource = null;
            countTextBlock.Text = "0";
            MessageBox.Show(
                exception.Message,
                LanguageManager.Format("LoadError", _repository.GetFriendlyTableName(tableName)),
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
            return null;
        }
    }

    private async void RefreshButton_Click(object sender, RoutedEventArgs e)
    {
        if (_isBusy)
        {
            return;
        }

        SetBusyState(true);
        try
        {
            await LoadAllTablesAsync();
        }
        finally
        {
            SetBusyState(false);
        }
    }

    private void DashboardButton_Click(object sender, RoutedEventArgs e)
    {
        if (_isBusy)
        {
            return;
        }

        var dashboardWindow = new DashboardWindow
        {
            Owner = this
        };

        dashboardWindow.ShowDialog();
    }

    private void BackupButton_Click(object sender, RoutedEventArgs e)
    {
        if (_isBusy || !_currentUser.HasAnyPermission(
                BackupService.CreateBackupPermission,
                BackupService.RestoreBackupPermission,
                BackupService.ViewBackupHistoryPermission))
        {
            return;
        }

        var backupWindow = new BackupWindow(_currentUser)
        {
            Owner = this
        };

        backupWindow.ShowDialog();
    }

    private void StartAutomaticProjectBackupScheduler()
    {
        if (!_backupService.CanCreateBackup)
        {
            return;
        }

        _autoProjectBackupTimer ??= new DispatcherTimer
        {
            Interval = AutoProjectBackupCheckInterval
        };

        _autoProjectBackupTimer.Tick -= AutoProjectBackupTimer_Tick;
        _autoProjectBackupTimer.Tick += AutoProjectBackupTimer_Tick;

        if (!_autoProjectBackupTimer.IsEnabled)
        {
            _autoProjectBackupTimer.Start();
        }
    }

    private async void AutoProjectBackupTimer_Tick(object? sender, EventArgs e)
    {
        await EnsureAutomaticProjectBackupAsync();
    }

    private async Task EnsureAutomaticProjectBackupAsync()
    {
        if (_autoProjectBackupInProgress || !_backupService.CanCreateBackup)
        {
            return;
        }

        var backupDirectory = _backupService.GetProjectBackupDirectory();
        if (HasAutomaticProjectBackupForDate(backupDirectory, DateTime.Now))
        {
            return;
        }

        _autoProjectBackupInProgress = true;
        try
        {
            var result = await _backupService.CreateProjectBackupAsync(automatic: true);
            if (result.Succeeded)
            {
                FooterMessageTextBlock.Text = LanguageManager.CurrentLanguage == AppLanguage.Russian
                    ? $"Авто backup создан в папке проекта: {backupDirectory}"
                    : $"Automatic backup created in the project folder: {backupDirectory}";
            }
        }
        catch
        {
            // Automatic backups are best-effort and should not interrupt admin work.
        }
        finally
        {
            _autoProjectBackupInProgress = false;
        }
    }

    private static bool HasAutomaticProjectBackupForDate(string backupDirectory, DateTime targetDate)
    {
        if (!Directory.Exists(backupDirectory))
        {
            return false;
        }

        var expectedPrefix = $"{DatabaseSettings.Database}_auto_";
        return Directory.EnumerateFiles(backupDirectory, "*.sql", SearchOption.TopDirectoryOnly)
            .Any(path =>
            {
                var fileName = Path.GetFileName(path);
                return fileName.StartsWith(expectedPrefix, StringComparison.OrdinalIgnoreCase) &&
                       File.GetLastWriteTime(path).Date == targetDate.Date;
            });
    }

    private void CurrentUserMenuButton_Click(object sender, RoutedEventArgs e)
    {
        if (_isBusy || !CanManageUsers())
        {
            return;
        }

        CurrentUserPopup.IsOpen = !CurrentUserPopup.IsOpen;
        e.Handled = true;
    }

    private void ManageUsersMenuButton_Click(object sender, RoutedEventArgs e)
    {
        if (_isBusy || !CanManageUsers())
        {
            return;
        }

        CurrentUserPopup.IsOpen = false;

        var usersWindow = new UsersWindow(_currentUser)
        {
            Owner = this
        };

        usersWindow.ShowDialog();
        e.Handled = true;
    }

    private void ReportsButton_Click(object sender, RoutedEventArgs e)
    {
        if (_isBusy)
        {
            return;
        }

        ReportsPopup.IsOpen = !ReportsPopup.IsOpen;
    }

    private async void OpenAllRecordsReportButton_Click(object sender, RoutedEventArgs e)
    {
        await OpenReportAsync(ReportKind.AllRecords);
    }

    private async void OpenFilteredReportButton_Click(object sender, RoutedEventArgs e)
    {
        await OpenReportAsync(ReportKind.FilteredData);
    }

    private async void OpenAnalyticsReportButton_Click(object sender, RoutedEventArgs e)
    {
        await OpenReportAsync(ReportKind.Analytics);
    }

    private async void OpenAuditReportButton_Click(object sender, RoutedEventArgs e)
    {
        await OpenReportAsync(ReportKind.Audit);
    }

    private Task OpenReportAsync(ReportKind kind)
    {
        if (_isBusy)
        {
            return Task.CompletedTask;
        }

        ReportsPopup.IsOpen = false;

        var filterWindow = new ReportFilterWindow(kind, GetSelectedTableName())
        {
            Owner = this
        };

        filterWindow.ShowDialog();
        return Task.CompletedTask;
    }

    private async void AddButton_Click(object sender, RoutedEventArgs e)
    {
        if (_isBusy)
        {
            return;
        }

        var addForm = new AddForm(_repository, GetSelectedTableName())
        {
            Owner = this
        };

        var result = addForm.ShowDialog();
        if (result != true)
        {
            return;
        }

        SetBusyState(true);
        try
        {
            await LoadAllTablesAsync();
        }
        finally
        {
            SetBusyState(false);
        }
    }

    private async void EditButton_Click(object sender, RoutedEventArgs e)
    {
        if (_isBusy)
        {
            return;
        }

        await EditSelectedRecordAsync(showSelectMessage: true);
    }

    private async void DeleteButton_Click(object sender, RoutedEventArgs e)
    {
        if (_isBusy)
        {
            return;
        }

        await DeleteSelectedRecordAsync(showSelectMessage: true);
    }

    private async Task EditSelectedRecordAsync(bool showSelectMessage)
    {
        if (GetCurrentGrid().SelectedItem is not DataRowView rowView)
        {
            if (showSelectMessage)
            {
                MessageBox.Show(LanguageManager.Get("SelectRowToEdit"), LanguageManager.Get("EditRecord"), MessageBoxButton.OK, MessageBoxImage.Information);
            }

            return;
        }

        SetBusyState(true);
        try
        {
            var sourceValues = BabyShopRepository.GetSourceValues(rowView);
            var initialValues = await _repository.GetRecordForEditAsync(GetSelectedTableName(), sourceValues);
            var editForm = new AddForm(_repository, GetSelectedTableName(), initialValues)
            {
                Owner = this
            };

            var result = editForm.ShowDialog();
            if (result == true)
            {
                await LoadAllTablesAsync();
            }
        }
        catch (Exception exception)
        {
            MessageBox.Show(exception.Message, LanguageManager.Get("EditRecord"), MessageBoxButton.OK, MessageBoxImage.Error);
        }
        finally
        {
            SetBusyState(false);
        }
    }

    private async Task DeleteSelectedRecordAsync(bool showSelectMessage)
    {
        if (GetCurrentGrid().SelectedItem is not DataRowView rowView)
        {
            if (showSelectMessage)
            {
                MessageBox.Show(LanguageManager.Get("SelectRowToDelete"), LanguageManager.Get("DeleteRecord"), MessageBoxButton.OK, MessageBoxImage.Information);
            }

            return;
        }

        if (GetSelectedTableName().Equals("CUSTOMER", StringComparison.OrdinalIgnoreCase))
        {
            MessageBox.Show(
                LanguageManager.Get("CustomerDeleteBlocked"),
                LanguageManager.Get("DeleteRecord"),
                MessageBoxButton.OK,
                MessageBoxImage.Information);
            return;
        }

        var confirmation = MessageBox.Show(
            LanguageManager.Get("DeleteConfirm"),
            LanguageManager.Get("DeleteRecord"),
            MessageBoxButton.YesNo,
            MessageBoxImage.Warning);

        if (confirmation != MessageBoxResult.Yes)
        {
            return;
        }

        SetBusyState(true);
        try
        {
            var sourceValues = BabyShopRepository.GetSourceValues(rowView);
            await _repository.DeleteRecordFromSourceAsync(GetSelectedTableName(), sourceValues);
            await LoadAllTablesAsync();
        }
        catch (Exception exception)
        {
            MessageBox.Show(exception.Message, LanguageManager.Get("DeleteRecord"), MessageBoxButton.OK, MessageBoxImage.Error);
        }
        finally
        {
            SetBusyState(false);
        }
    }

    private async void DataGrid_MouseDoubleClick(object sender, MouseButtonEventArgs e)
    {
        if (_isBusy || sender is not DataGrid dataGrid)
        {
            return;
        }

        var row = FindVisualParent<DataGridRow>(e.OriginalSource as DependencyObject);
        if (row?.Item is not DataRowView)
        {
            return;
        }

        dataGrid.SelectedItem = row.Item;
        await EditSelectedRecordAsync(showSelectMessage: false);
    }

    private async void DataGrid_PreviewMouseRightButtonUp(object sender, MouseButtonEventArgs e)
    {
        if (_isBusy || sender is not DataGrid dataGrid)
        {
            return;
        }

        var row = FindVisualParent<DataGridRow>(e.OriginalSource as DependencyObject);
        if (row?.Item is not DataRowView)
        {
            return;
        }

        dataGrid.SelectedItem = row.Item;
        await DeleteSelectedRecordAsync(showSelectMessage: false);
        e.Handled = true;
    }

    private void NavButton_Click(object sender, RoutedEventArgs e)
    {
        if (sender is not RadioButton { Tag: string tagStr } || !int.TryParse(tagStr, out var index))
        {
            return;
        }

        _selectedTabIndex = index;
        ReportsPopup.IsOpen = false;
        SearchBox.Text = string.Empty;

        CustomerGrid.Visibility = index == 0 ? Visibility.Visible : Visibility.Collapsed;
        FabricGrid.Visibility = index == 1 ? Visibility.Visible : Visibility.Collapsed;
        ProductGrid.Visibility = index == 2 ? Visibility.Visible : Visibility.Collapsed;
        CustomerOrderGrid.Visibility = index == 3 ? Visibility.Visible : Visibility.Collapsed;
        OrderProductGrid.Visibility = index == 4 ? Visibility.Visible : Visibility.Collapsed;
        OrderStatusFilterPanel.Visibility = index == 3 ? Visibility.Visible : Visibility.Collapsed;
        RecordsPanel.Margin = index == 3
            ? new Thickness(38, 76, 28, 28)
            : new Thickness(38, 18, 28, 28);

        ApplyPageHeader();
        ApplySearch(SearchBox.Text);
    }

    private void SearchBox_TextChanged(object sender, TextChangedEventArgs e)
    {
        SearchPlaceholderTextBlock.Visibility = string.IsNullOrWhiteSpace(SearchBox.Text)
            ? Visibility.Visible
            : Visibility.Collapsed;
        ApplySearch(SearchBox.Text);
    }

    private void OrderStatusFilter_Changed(object sender, RoutedEventArgs e)
    {
        if (!IsLoaded)
        {
            return;
        }

        ApplySearch(SearchBox.Text);
    }

    private async void LanguageToggleButton_Click(object sender, RoutedEventArgs e)
    {
        if (!_languageSelectorReady || _isBusy)
        {
            return;
        }

        var language = LanguageManager.CurrentLanguage == AppLanguage.Russian
            ? AppLanguage.English
            : AppLanguage.Russian;

        LanguageManager.SetLanguage(language);
        ApplyLocalization();

        if (!IsLoaded)
        {
            return;
        }

        SetBusyState(true);
        try
        {
            await LoadAllTablesAsync();
        }
        finally
        {
            SetBusyState(false);
        }
    }

    private void ApplySearch(string query)
    {
        query = query.Trim();
        var imageColumnNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "Image",
            "Image Path",
            LanguageManager.GetColumnName("image_path") ?? "Image"
        };

        string BuildSearchFilter(DataView view)
        {
            if (string.IsNullOrEmpty(query))
            {
                return string.Empty;
            }

            var columns = view.Table?.Columns;
            if (columns == null || columns.Count == 0)
            {
                return string.Empty;
            }

            var escaped = EscapeRowFilterValue(query);
            var clauses = new List<string>();

            foreach (DataColumn column in columns)
            {
                if (column.ColumnName.StartsWith("__src_", StringComparison.OrdinalIgnoreCase) ||
                    column.ColumnName.StartsWith("__preview_", StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                if (imageColumnNames.Contains(column.ColumnName))
                {
                    continue;
                }

                clauses.Add(column.DataType == typeof(string)
                    ? $"[{column.ColumnName}] LIKE '%{escaped}%'"
                    : $"Convert([{column.ColumnName}], 'System.String') LIKE '%{escaped}%'");
            }

            return clauses.Count == 0 ? string.Empty : $"({string.Join(" OR ", clauses)})";
        }

        void Filter(DataView? view, bool includeOrderStatusFilter = false)
        {
            if (view == null)
            {
                return;
            }

            var filters = new List<string>();
            var searchFilter = BuildSearchFilter(view);
            if (!string.IsNullOrWhiteSpace(searchFilter))
            {
                filters.Add(searchFilter);
            }

            if (includeOrderStatusFilter)
            {
                var statusFilter = BuildOrderStatusFilter(view);
                if (!string.IsNullOrWhiteSpace(statusFilter))
                {
                    filters.Add(statusFilter);
                }
            }

            try
            {
                view.RowFilter = filters.Count == 0 ? string.Empty : string.Join(" AND ", filters);
            }
            catch (EvaluateException)
            {
                view.RowFilter = string.Empty;
            }
            catch (SyntaxErrorException)
            {
                view.RowFilter = string.Empty;
            }
        }

        Filter(_customerView);
        Filter(_fabricView);
        Filter(_productView);
        Filter(_orderView, includeOrderStatusFilter: true);
        Filter(_orderProductView);
    }

    private static string EscapeRowFilterValue(string value)
    {
        return value
            .Replace("'", "''")
            .Replace("[", "[[]")
            .Replace("]", "[]]")
            .Replace("%", "[%]")
            .Replace("*", "[*]");
    }

    private string BuildOrderStatusFilter(DataView view)
    {
        var selectedStatuses = new List<string>();
        if (OrderStatusPendingCheckBox.IsChecked == true)
        {
            selectedStatuses.Add("Pending");
        }

        if (OrderStatusShippedCheckBox.IsChecked == true)
        {
            selectedStatuses.Add("Shipped");
        }

        if (OrderStatusCompletedCheckBox.IsChecked == true)
        {
            selectedStatuses.Add("Completed");
        }

        if (selectedStatuses.Count == 0)
        {
            return "1 = 0";
        }

        var statusColumn = view.Table?.Columns.Contains("__src_order_status") == true
            ? "__src_order_status"
            : view.Table?.Columns.Cast<DataColumn>().FirstOrDefault(column => column.ColumnName.Contains("СЃС‚Р°С‚СѓСЃ", StringComparison.OrdinalIgnoreCase) ||
                                                                              column.ColumnName.Contains("status", StringComparison.OrdinalIgnoreCase))?.ColumnName;

        if (string.IsNullOrWhiteSpace(statusColumn))
        {
            return string.Empty;
        }

        return string.Join(" OR ", selectedStatuses.Select(status => $"[{statusColumn}] = '{status}'")) is { } clause
            ? $"({clause})"
            : string.Empty;
    }

    private void ApplyFreshOrderSort()
    {
        if (_orderView?.Table == null)
        {
            return;
        }

        if (_orderView.Table.Columns.Contains("__src_start_date"))
        {
            _orderView.Sort = _orderView.Table.Columns.Contains("__src_order_id")
                ? "[__src_start_date] DESC, [__src_order_id] DESC"
                : "[__src_start_date] DESC";
            return;
        }

        var startDateColumn = _orderView.Table.Columns
            .Cast<DataColumn>()
            .FirstOrDefault(column => column.ColumnName.Contains("РґР°С‚Р° РЅР°С‡Р°Р»Р°", StringComparison.OrdinalIgnoreCase) ||
                                      column.ColumnName.Contains("start", StringComparison.OrdinalIgnoreCase));

        if (startDateColumn is not null)
        {
            _orderView.Sort = $"[{startDateColumn.ColumnName}] DESC";
        }
    }

    private static void ApplyDefaultGridSort(string tableName, DataView view)
    {
        if (view.Table.Columns.Count == 0)
        {
            return;
        }

        var sortClause = tableName.ToUpperInvariant() switch
        {
            "PRODUCTFABRICVIEW" => BuildSortClause(view.Table, "__src_product_id"),
            "CUSTOMERORDERSVIEW" => BuildSortClause(view.Table, "__src_order_id"),
            "ORDERPRODUCTVIEW" => BuildNumberSortClause(view.Table),
            "CUSTOMERVIEW" => BuildSortClause(view.Table, "__src_customer_id"),
            "FABRICVIEW" => BuildSortClause(view.Table, "__src_fabric_id"),
            _ => string.Empty
        };

        if (string.IsNullOrWhiteSpace(sortClause))
        {
            var fallbackColumnName = view.Table.Columns[0].ColumnName;
            if (string.IsNullOrWhiteSpace(fallbackColumnName))
            {
                return;
            }

            sortClause = $"[{fallbackColumnName}] ASC";
        }

        view.Sort = sortClause;
    }

    private static string BuildNumberSortClause(DataTable table)
    {
        var numberColumn = table.Columns
            .Cast<DataColumn>()
            .FirstOrDefault(column =>
                string.Equals(column.ColumnName, "№", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(column.ColumnName, "No.", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(column.ColumnName, "пїЅ", StringComparison.OrdinalIgnoreCase));

        return numberColumn is null
            ? string.Empty
            : $"[{numberColumn.ColumnName}] ASC";
    }

    private static string BuildSortClause(DataTable table, params string[] columnNames)
    {
        var existingColumns = columnNames
            .Where(columnName => table.Columns.Contains(columnName))
            .Select(columnName => $"[{columnName}] ASC")
            .ToArray();

        return existingColumns.Length == 0
            ? string.Empty
            : string.Join(", ", existingColumns);
    }

    private string GetSelectedTableName() => _selectedTabIndex switch
    {
        0 => "CUSTOMER",
        1 => "FABRIC",
        2 => "PRODUCTT",
        3 => "CUSTOMER_ORDER",
        4 => "ORDER_PRODUCT",
        _ => "CUSTOMER"
    };

    private DataView? GetCurrentView() => _selectedTabIndex switch
    {
        0 => _customerView,
        1 => _fabricView,
        2 => _productView,
        3 => _orderView,
        4 => _orderProductView,
        _ => _customerView
    };

    private DataGrid GetCurrentGrid() => _selectedTabIndex switch
    {
        0 => CustomerGrid,
        1 => FabricGrid,
        2 => ProductGrid,
        3 => CustomerOrderGrid,
        4 => OrderProductGrid,
        _ => CustomerGrid
    };

    private void ApplyLocalization()
    {
        Title = LanguageManager.Get("AppTitle");
        BrandTitleTextBlock.Text = LanguageManager.Get("AppTitle");
        BrandSubtitleTextBlock.Text = LanguageManager.Get("BrandSubtitle");
        LanguageLabelTextBlock.Text = LanguageManager.Get("Language");
        NavCustomersTextBlock.Text = LanguageManager.Get("Customers");
        NavFabricsTextBlock.Text = LanguageManager.Get("Fabrics");
        NavProductsTextBlock.Text = LanguageManager.Get("Products");
        NavOrdersTextBlock.Text = LanguageManager.Get("Orders");
        NavOrderItemsTextBlock.Text = LanguageManager.Get("OrderItems");
        CustomerStatLabelTextBlock.Text = LanguageManager.Get("Customers");
        FabricStatLabelTextBlock.Text = LanguageManager.Get("Fabrics");
        ProductStatLabelTextBlock.Text = LanguageManager.Get("Products");
        OrderStatLabelTextBlock.Text = LanguageManager.Get("Orders");
        OrderItemStatLabelTextBlock.Text = LanguageManager.Get("OrderItems");
        OrderStatusFilterLabelTextBlock.Text = LanguageManager.Get("OrderStatusFilter");
        OrderStatusPendingCheckBox.Content = LanguageManager.Get("StatusPending");
        OrderStatusShippedCheckBox.Content = LanguageManager.Get("StatusShipped");
        OrderStatusCompletedCheckBox.Content = LanguageManager.Get("StatusCompleted");
        ApplyActionButtonLabels();
        EditButtonTextBlock.Text = LanguageManager.Get("EditRecord");
        DeleteButtonTextBlock.Text = LanguageManager.Get("DeleteRecord");
        RefreshButtonTextBlock.Text = LanguageManager.Get("Refresh");
        DashboardButton.ToolTip = LanguageManager.Get("OpenDashboard");
        ReportsButton.ToolTip = LanguageManager.Get("OpenReports");
        BackupButton.ToolTip = LanguageManager.Get("OpenBackup");
        CurrentUserMenuButton.ToolTip = LanguageManager.CurrentLanguage == AppLanguage.Russian ? "Меню пользователя" : "User menu";
        ManageUsersMenuTitleTextBlock.Text = LanguageManager.CurrentLanguage == AppLanguage.Russian ? "Пользователи" : "Users";
        ManageUsersMenuNoteTextBlock.Text = LanguageManager.CurrentLanguage == AppLanguage.Russian
            ? "Открыть таблицу пользователей из представления базы данных."
            : "Open the users table from the database view.";
        ReportsPopupTitleTextBlock.Text = LanguageManager.Get("ReportsMenuTitle");
        AllRecordsReportButtonTitleTextBlock.Text = LanguageManager.Get("ReportMenuAllRecords");
        AllRecordsReportButtonNoteTextBlock.Text = LanguageManager.Get("ReportMenuAllRecordsNote");
        FilteredReportButtonTitleTextBlock.Text = LanguageManager.Get("ReportMenuFiltered");
        FilteredReportButtonNoteTextBlock.Text = LanguageManager.Get("ReportMenuFilteredNote");
        AnalyticsReportButtonTitleTextBlock.Text = LanguageManager.Get("ReportMenuAnalytics");
        AnalyticsReportButtonNoteTextBlock.Text = LanguageManager.Get("ReportMenuAnalyticsNote");
        AuditReportButtonTitleTextBlock.Text = LanguageManager.CurrentLanguage == AppLanguage.Russian ? "Журнал аудита" : "Audit log";
        AuditReportButtonNoteTextBlock.Text = LanguageManager.CurrentLanguage == AppLanguage.Russian
            ? "Входы, ошибки авторизации, регистрация и действия над данными."
            : "Logins, authorization failures, registration, and data changes.";
        SearchBox.ToolTip = LanguageManager.Get("SearchPlaceholder");
        SearchPlaceholderTextBlock.Text = LanguageManager.Get("SearchPlaceholder");
        UpdateLanguageToggleVisual();
        UpdateCurrentUserBadge();
        UpdateCurrentUserMenuState();
        ApplyPageHeader();

        LastRefreshTextBlock.Text = _lastRefreshAt.HasValue
            ? LanguageManager.Format("LastRefreshed", _lastRefreshAt.Value.ToString("g"))
            : LanguageManager.Get("NoDataLoaded");

        if (StatusDot.Fill == (Brush)FindResource("SuccessBrush"))
        {
            StatusTextBlock.Text = LanguageManager.Get("ConnectedToMySql");
        }
        else if (!_isBusy)
        {
            StatusTextBlock.Text = LanguageManager.Get("Connecting");
        }

        FooterMessageTextBlock.Text = _lastRefreshAt.HasValue
            ? LanguageManager.Get("AllTablesSynced")
            : LanguageManager.Get("FooterDefault");
    }

    private void ApplyPageHeader()
    {
        (PageTitleTextBlock.Text, PageSubtitleTextBlock.Text) = _selectedTabIndex switch
        {
            0 => (LanguageManager.Get("CustomerDirectoryTitle"), LanguageManager.Get("CustomerDirectorySubtitle")),
            1 => (LanguageManager.Get("FabricInventoryTitle"), LanguageManager.Get("FabricInventorySubtitle")),
            2 => (LanguageManager.Get("ProductCatalogueTitle"), LanguageManager.Get("ProductCatalogueSubtitle")),
            3 => (LanguageManager.Get("CustomerOrdersTitle"), LanguageManager.Get("CustomerOrdersSubtitle")),
            4 => (LanguageManager.Get("OrderItemsTitle"), LanguageManager.Get("OrderItemsSubtitle")),
            _ => (PageTitleTextBlock.Text, PageSubtitleTextBlock.Text)
        };

        ApplyActionButtonLabels();
    }

    private void ApplyActionButtonLabels()
    {
        var noun = LanguageManager.CurrentLanguage == AppLanguage.Russian
            ? _selectedTabIndex switch
            {
                0 => "клиента",
                1 => "ткань",
                2 => "товар",
                3 => "заказ",
                4 => "позицию",
                _ => "запись"
            }
            : _selectedTabIndex switch
            {
                0 => "Client",
                1 => "Fabric",
                2 => "Product",
                3 => "Order",
                4 => "Item",
                _ => "Record"
            };

        var addPrefix = LanguageManager.CurrentLanguage == AppLanguage.Russian ? "Добавить" : "Add";
        AddButtonTextBlock.Text = $"{addPrefix} {noun}";
    }

    private string GetCurrentPluralTableName()
    {
        return _selectedTabIndex switch
        {
            0 => LanguageManager.Get("Customers"),
            1 => LanguageManager.Get("Fabrics"),
            2 => LanguageManager.Get("Products"),
            3 => LanguageManager.Get("Orders"),
            4 => LanguageManager.Get("OrderItems"),
            _ => LanguageManager.Get("Customers")
        };
    }

    private void UpdateLanguageToggleVisual()
    {
        var isRussian = LanguageManager.CurrentLanguage == AppLanguage.Russian;
        Grid.SetRow(LanguageToggleThumb, isRussian ? 0 : 1);
        LanguageToggleThumb.Background = isRussian
            ? (Brush)FindResource("AccentLightBrush")
            : (Brush)FindResource("AccentStrongBrush");
        LanguageRuTextBlock.Foreground = isRussian
            ? (Brush)FindResource("AccentStrongBrush")
            : (Brush)FindResource("TextMutedBrush");
        LanguageEnTextBlock.Foreground = isRussian
            ? (Brush)FindResource("TextMutedBrush")
            : Brushes.White;
    }

    private void UpdateCurrentUserBadge()
    {
        CurrentUsernameTextBlock.Text = _currentUser.Username;
        CurrentRoleTextBlock.Text = string.IsNullOrWhiteSpace(_currentUser.RoleName)
            ? LanguageManager.Get("BackupUserRoleDefault")
            : CultureInfo.CurrentCulture.TextInfo.ToTitleCase(_currentUser.RoleName);

        var usernameParts = _currentUser.Username
            .Split([' ', '.', '_', '-'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        var initials = usernameParts.Length == 0
            ? "AD"
            : string.Concat(usernameParts.Take(2).Select(part => char.ToUpperInvariant(part[0])));

        CurrentUserInitialsTextBlock.Text = initials;
    }

    private void UpdateCurrentUserMenuState()
    {
        var canManageUsers = CanManageUsers();
        CurrentUserMenuButton.IsEnabled = canManageUsers && !_isBusy;
        CurrentUserChevronPath.Visibility = canManageUsers ? Visibility.Visible : Visibility.Collapsed;
        ManageUsersMenuButton.Visibility = canManageUsers ? Visibility.Visible : Visibility.Collapsed;

        if (!canManageUsers)
        {
            CurrentUserPopup.IsOpen = false;
        }
    }

    private bool CanManageUsers()
    {
        return _currentUser.IsAdmin || _currentUser.HasPermission(ManageUsersPermission);
    }

    private static IEnumerable<T> FindVisualChildren<T>(DependencyObject parent) where T : DependencyObject
    {
        for (var i = 0; i < VisualTreeHelper.GetChildrenCount(parent); i++)
        {
            var child = VisualTreeHelper.GetChild(parent, i);
            if (child is T typedChild)
            {
                yield return typedChild;
            }

            foreach (var nestedChild in FindVisualChildren<T>(child))
            {
                yield return nestedChild;
            }
        }
    }

    private static T? FindVisualParent<T>(DependencyObject? child) where T : DependencyObject
    {
        while (child is not null)
        {
            if (child is T typedParent)
            {
                return typedParent;
            }

            child = VisualTreeHelper.GetParent(child);
        }

        return null;
    }

    private void DataGrid_AutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
    {
        if (e.PropertyName.StartsWith("__src_", StringComparison.OrdinalIgnoreCase))
        {
            e.Cancel = true;
            return;
        }

        if (e.PropertyName.Equals("пїЅ", StringComparison.OrdinalIgnoreCase) ||
            e.PropertyName.Equals("No.", StringComparison.OrdinalIgnoreCase) ||
            e.PropertyName.Equals("№", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(e.Column.Header?.ToString(), "№", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(e.Column.Header?.ToString(), "No.", StringComparison.OrdinalIgnoreCase))
        {
            e.Column.Width = new DataGridLength(60);

            if (e.Column is DataGridTextColumn textColumn)
            {
                var accentBrush = TryFindResource("AccentBrush") as Brush ??
                                  TryFindResource("AccentStrongBrush") as Brush;

                if (accentBrush is not null)
                {
                    var elementStyle = new Style(typeof(TextBlock));
                    elementStyle.Setters.Add(new Setter(TextBlock.ForegroundProperty, accentBrush));
                    elementStyle.Setters.Add(new Setter(TextBlock.FontWeightProperty, FontWeights.Normal));
                    elementStyle.Setters.Add(new Setter(TextBlock.TextAlignmentProperty, TextAlignment.Left));
                    elementStyle.Setters.Add(new Setter(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Left));
                    elementStyle.Setters.Add(new Setter(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center));
                    textColumn.ElementStyle = elementStyle;
                }
            }
        }
    }

    private void DataGrid_ImageAutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
    {
        if (e.PropertyName.StartsWith("__preview_", StringComparison.OrdinalIgnoreCase))
        {
            e.Cancel = true;
            return;
        }

        if (sender != ProductGrid)
        {
            return;
        }

        var localizedImageHeader = LanguageManager.GetColumnName("image_path") ?? "Image";
        if (!e.PropertyName.Equals("Image Path", StringComparison.OrdinalIgnoreCase) &&
            !e.PropertyName.Equals("Image", StringComparison.OrdinalIgnoreCase) &&
            !e.PropertyName.Equals(localizedImageHeader, StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        var borderFactory = new FrameworkElementFactory(typeof(Border));
        borderFactory.SetValue(Border.WidthProperty, 56d);
        borderFactory.SetValue(Border.HeightProperty, 56d);
        borderFactory.SetValue(Border.CornerRadiusProperty, new CornerRadius(8));
        borderFactory.SetValue(Border.BorderBrushProperty, (Brush)FindResource("LineBrush"));
        borderFactory.SetValue(Border.BorderThicknessProperty, new Thickness(1));
        borderFactory.SetValue(Border.BackgroundProperty, Brushes.White);
        borderFactory.SetValue(Border.MarginProperty, new Thickness(0, 4, 0, 4));
        borderFactory.SetValue(Border.HorizontalAlignmentProperty, HorizontalAlignment.Center);

        var imageFactory = new FrameworkElementFactory(typeof(Image));
        imageFactory.SetBinding(Image.SourceProperty, new Binding("__preview_image_path"));
        imageFactory.SetValue(Image.StretchProperty, Stretch.UniformToFill);
        imageFactory.SetValue(Image.SnapsToDevicePixelsProperty, true);
        borderFactory.AppendChild(imageFactory);

        e.Column = new DataGridTemplateColumn
        {
            Header = e.Column.Header,
            Width = new DataGridLength(88),
            SortMemberPath = e.PropertyName,
            CellTemplate = new DataTemplate
            {
                VisualTree = borderFactory
            }
        };

        e.Column.DisplayIndex = 1;
    }

    private void CustomerOrderGrid_AutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
    {
        if (IsOrderItemsColumnName(e.PropertyName))
        {
            e.Cancel = true;
            return;
        }

        if (sender is not DataGrid)
        {
            return;
        }

        var headerText = e.Column.Header?.ToString() ?? string.Empty;
        var normalizedHeader = headerText.Trim().ToLowerInvariant();
        var normalizedProperty = e.PropertyName.Trim().ToLowerInvariant();

        if (e.Column is DataGridTextColumn textColumn)
        {
            var centeredStyle = new Style(typeof(TextBlock));
            centeredStyle.Setters.Add(new Setter(TextBlock.FontWeightProperty, FontWeights.Normal));
            centeredStyle.Setters.Add(new Setter(TextBlock.TextAlignmentProperty, TextAlignment.Left));
            centeredStyle.Setters.Add(new Setter(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Left));
            centeredStyle.Setters.Add(new Setter(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center));
            centeredStyle.Setters.Add(new Setter(TextBlock.TextTrimmingProperty, TextTrimming.CharacterEllipsis));
            textColumn.ElementStyle = centeredStyle;
        }

        if (normalizedProperty is "no." or "пїЅ" or "№" || normalizedHeader is "№" or "no.")
        {
            e.Column.Width = new DataGridLength(64);
            e.Column.Header = "№";
            return;
        }

        if (normalizedHeader.Contains("фио") || normalizedHeader.Contains("client") || normalizedProperty.Contains("fullname"))
        {
            e.Column.Width = new DataGridLength(190);
            return;
        }

        if (normalizedHeader.Contains("адрес") || normalizedHeader.Contains("address"))
        {
            e.Column.Width = new DataGridLength(210);
            return;
        }

        if (normalizedHeader.Contains("дата начала") || normalizedHeader.Contains("start"))
        {
            e.Column.Width = new DataGridLength(190);
            return;
        }

        if (normalizedHeader.Contains("дата окончания") || normalizedHeader.Contains("end"))
        {
            e.Column.Width = new DataGridLength(190);
            return;
        }

        if (normalizedHeader.Contains("статус") || normalizedProperty.Contains("status"))
        {
            e.Column.Width = new DataGridLength(118);
            e.Column.Header = LanguageManager.CurrentLanguage == AppLanguage.Russian ? "Статус" : "Status";
            return;
        }

        if (normalizedHeader.Contains("сумма") || normalizedProperty.Contains("total_cost"))
        {
            e.Column.Width = new DataGridLength(128);
            e.Column.Header = LanguageManager.CurrentLanguage == AppLanguage.Russian ? "Сумма" : "Total";
        }
    }

    private void CustomerOrderGrid_AutoGeneratedColumns(object? sender, EventArgs e)
    {
        if (sender is DataGrid dataGrid)
        {
            EnsureOrderDetailsButtonColumn(dataGrid);
            foreach (var column in dataGrid.Columns)
            {
                if (string.Equals(column.Header?.ToString(), "Детали", StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(column.Header?.ToString(), "Details", StringComparison.OrdinalIgnoreCase))
                {
                    column.Width = new DataGridLength(88);
                }
            }
        }
    }

    private void SetBusyState(bool isBusy)
    {
        _isBusy = isBusy;
        RefreshButton.IsEnabled = !isBusy;
        AddButton.IsEnabled = !isBusy;
        EditButton.IsEnabled = !isBusy;
        DeleteButton.IsEnabled = !isBusy;
        DashboardButton.IsEnabled = !isBusy;
        ReportsButton.IsEnabled = !isBusy;
        BackupButton.IsEnabled = !isBusy && _currentUser.HasAnyPermission(
            BackupService.CreateBackupPermission,
            BackupService.RestoreBackupPermission,
            BackupService.ViewBackupHistoryPermission);
        CurrentUserMenuButton.IsEnabled = !isBusy && CanManageUsers();
        if (isBusy)
        {
            ReportsPopup.IsOpen = false;
            CurrentUserPopup.IsOpen = false;
        }
        Mouse.OverrideCursor = isBusy ? Cursors.Wait : null;
    }

    private void EnsureOrderDetailsButtonColumn(DataGrid dataGrid)
    {
        var existingColumn = dataGrid.Columns.FirstOrDefault(column =>
            string.Equals(column.SortMemberPath, OrderDetailsColumnSortKey, StringComparison.OrdinalIgnoreCase));

        if (existingColumn is not null)
        {
            dataGrid.Columns.Remove(existingColumn);
        }

        var iconPathFactory = new FrameworkElementFactory(typeof(System.Windows.Shapes.Path));
        iconPathFactory.SetValue(System.Windows.Shapes.Path.WidthProperty, 14d);
        iconPathFactory.SetValue(System.Windows.Shapes.Path.HeightProperty, 16d);
        iconPathFactory.SetValue(System.Windows.Shapes.Path.StretchProperty, Stretch.Uniform);
        iconPathFactory.SetValue(System.Windows.Shapes.Path.StrokeProperty, (Brush)FindResource("AccentStrongBrush"));
        iconPathFactory.SetValue(System.Windows.Shapes.Path.FillProperty, Brushes.Transparent);
        iconPathFactory.SetValue(System.Windows.Shapes.Path.StrokeThicknessProperty, 1.6d);
        iconPathFactory.SetValue(System.Windows.Shapes.Path.StrokeStartLineCapProperty, PenLineCap.Round);
        iconPathFactory.SetValue(System.Windows.Shapes.Path.StrokeEndLineCapProperty, PenLineCap.Round);
        iconPathFactory.SetValue(System.Windows.Shapes.Path.StrokeLineJoinProperty, PenLineJoin.Round);
        iconPathFactory.SetValue(System.Windows.Shapes.Path.DataProperty, Geometry.Parse("M4,1.5 L10.5,1.5 L14,5 L14,14.5 L4,14.5 Z M10.5,1.5 L10.5,5 L14,5 M6.5,7.5 L11.5,7.5 M6.5,10.5 L11.5,10.5"));

        var viewboxFactory = new FrameworkElementFactory(typeof(Viewbox));
        viewboxFactory.SetValue(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Center);
        viewboxFactory.SetValue(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center);
        viewboxFactory.AppendChild(iconPathFactory);

        var buttonFactory = new FrameworkElementFactory(typeof(Button));
        buttonFactory.SetValue(FrameworkElement.WidthProperty, 38d);
        buttonFactory.SetValue(FrameworkElement.HeightProperty, 38d);
        buttonFactory.SetValue(FrameworkElement.MarginProperty, new Thickness(0));
        buttonFactory.SetValue(Control.PaddingProperty, new Thickness(0));
        buttonFactory.SetValue(Control.CursorProperty, Cursors.Hand);
        buttonFactory.SetValue(Control.ForegroundProperty, (Brush)FindResource("AccentStrongBrush"));
        buttonFactory.SetValue(Control.BackgroundProperty, Brushes.Transparent);
        buttonFactory.SetValue(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Center);
        buttonFactory.SetValue(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center);
        buttonFactory.SetValue(FrameworkElement.ToolTipProperty, LanguageManager.CurrentLanguage == AppLanguage.Russian ? "Детали" : "Details");
        buttonFactory.SetValue(Control.TemplateProperty, BuildOrderDetailsButtonTemplate());
        buttonFactory.SetBinding(FrameworkElement.TagProperty, new Binding("__src_order_id"));
        buttonFactory.AddHandler(Button.ClickEvent, new RoutedEventHandler(OrderDetailsButton_Click));
        buttonFactory.AppendChild(viewboxFactory);


        dataGrid.Columns.Add(new DataGridTemplateColumn
        {
            Header = LanguageManager.CurrentLanguage == AppLanguage.Russian ? "Детали" : "Details",
            Width = new DataGridLength(88),
            SortMemberPath = OrderDetailsColumnSortKey,
            IsReadOnly = true,
            CellTemplate = new DataTemplate
            {
                VisualTree = buttonFactory
            }
        });
        if (dataGrid.Columns.Count > 0)
        {
            dataGrid.Columns[^1].DisplayIndex = dataGrid.Columns.Count - 1;
        }
    }

    private static bool IsOrderTotalColumn(DataGridColumn column)
    {
        var headerText = column.Header?.ToString();
        return string.Equals(column.SortMemberPath, "TOTAL_COST", StringComparison.OrdinalIgnoreCase) ||
               string.Equals(column.SortMemberPath, "total_cost", StringComparison.OrdinalIgnoreCase) ||
               string.Equals(headerText, "Сумма заказа", StringComparison.OrdinalIgnoreCase) ||
               string.Equals(headerText, "Order Total", StringComparison.OrdinalIgnoreCase);
    }

    private static ControlTemplate BuildOrderDetailsButtonTemplate()
    {
        var borderFactory = new FrameworkElementFactory(typeof(Border));
        borderFactory.Name = "RootBorder";
        borderFactory.SetValue(Border.BackgroundProperty, Brushes.Transparent);
        borderFactory.SetValue(Border.BorderBrushProperty, Brushes.Transparent);
        borderFactory.SetValue(Border.BorderThicknessProperty, new Thickness(0));
        borderFactory.SetValue(Border.CornerRadiusProperty, new CornerRadius(0));

        var presenterFactory = new FrameworkElementFactory(typeof(ContentPresenter));
        presenterFactory.SetValue(HorizontalAlignmentProperty, HorizontalAlignment.Center);
        presenterFactory.SetValue(VerticalAlignmentProperty, VerticalAlignment.Center);
        borderFactory.AppendChild(presenterFactory);

        var template = new ControlTemplate(typeof(Button))
        {
            VisualTree = borderFactory
        };

        var hoverTrigger = new Trigger
        {
            Property = UIElement.IsMouseOverProperty,
            Value = true
        };
        hoverTrigger.Setters.Add(new Setter(UIElement.OpacityProperty, 0.82d, "RootBorder"));


        var pressedTrigger = new Trigger
        {
            Property = Button.IsPressedProperty,
            Value = true
        };
        pressedTrigger.Setters.Add(new Setter(UIElement.OpacityProperty, 0.68d, "RootBorder"));

        template.Triggers.Add(hoverTrigger);
        template.Triggers.Add(pressedTrigger);
        return template;
    }

    private void EnsureOrderDetailsButtonColumnLegacy(DataGrid dataGrid)
    {
        var existingColumn = dataGrid.Columns.FirstOrDefault(column =>
            string.Equals(column.SortMemberPath, OrderDetailsColumnSortKey, StringComparison.OrdinalIgnoreCase));

        if (existingColumn is not null)
        {
            dataGrid.Columns.Remove(existingColumn);
        }

        var buttonFactory = new FrameworkElementFactory(typeof(Button));
        buttonFactory.SetValue(Button.ContentProperty, LanguageManager.CurrentLanguage == AppLanguage.Russian ? "Детали" : "Details");
        buttonFactory.SetValue(Button.PaddingProperty, new Thickness(16, 9, 16, 9));
        buttonFactory.SetValue(Button.MarginProperty, new Thickness(8, 6, 8, 6));
        buttonFactory.SetValue(Button.FontSizeProperty, 13d);
        buttonFactory.SetValue(Button.FontWeightProperty, FontWeights.SemiBold);
        buttonFactory.SetValue(Button.CursorProperty, Cursors.Hand);
        buttonFactory.SetValue(Button.ForegroundProperty, (Brush)FindResource("TextDarkBrush"));
        buttonFactory.SetValue(Button.BackgroundProperty, (Brush)FindResource("PeachBrush"));
        buttonFactory.SetValue(Button.BorderBrushProperty, (Brush)FindResource("BorderBrush"));
        buttonFactory.SetValue(Button.BorderThicknessProperty, new Thickness(1));
        buttonFactory.SetValue(Button.HorizontalAlignmentProperty, HorizontalAlignment.Center);
        buttonFactory.SetValue(Button.VerticalAlignmentProperty, VerticalAlignment.Center);
        buttonFactory.AddHandler(Button.ClickEvent, new RoutedEventHandler(OrderDetailsButton_Click));
        buttonFactory.SetBinding(FrameworkElement.TagProperty, new Binding("__src_order_id"));

        dataGrid.Columns.Add(new DataGridTemplateColumn
        {
            Header = LanguageManager.CurrentLanguage == AppLanguage.Russian ? "Детали" : "Details",
            Width = new DataGridLength(126),
            SortMemberPath = OrderDetailsColumnSortKey,
            IsReadOnly = true,
            CellTemplate = new DataTemplate
            {
                VisualTree = buttonFactory
            }
        });
    }

    private void OrderDetailsButton_Click(object sender, RoutedEventArgs e)
    {
        if (_isBusy || sender is not Button button || button.DataContext is not DataRowView rowView)
        {
            return;
        }

        var sourceValues = BabyShopRepository.GetSourceValues(rowView);
        if (!sourceValues.TryGetValue("order_id", out var rawOrderId) || rawOrderId is null || rawOrderId is DBNull)
        {
            MessageBox.Show(
                LanguageManager.CurrentLanguage == AppLanguage.Russian ? "Не удалось определить ID заказа." : "Could not determine the order ID.",
                Title,
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
            return;
        }

        CustomerOrderGrid.SelectedItem = rowView;

        var orderDetailsWindow = new OrderDetailsWindow(Convert.ToInt32(rawOrderId, CultureInfo.CurrentCulture))
        {
            Owner = this
        };

        orderDetailsWindow.ShowDialog();
        e.Handled = true;
    }

    private static bool IsOrderItemsColumnName(string propertyName)
    {
        return propertyName.Equals("order_items", StringComparison.OrdinalIgnoreCase) ||
               propertyName.Equals("Order Items", StringComparison.OrdinalIgnoreCase) ||
               propertyName.Equals("Состав заказа", StringComparison.OrdinalIgnoreCase) ||
               string.Equals(propertyName, LanguageManager.GetColumnName("order_items"), StringComparison.OrdinalIgnoreCase);
    }

    protected override void OnClosed(EventArgs e)
    {
        if (_autoProjectBackupTimer is not null)
        {
            _autoProjectBackupTimer.Stop();
            _autoProjectBackupTimer.Tick -= AutoProjectBackupTimer_Tick;
        }

        base.OnClosed(e);
    }
}
